name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      
      - name: Install cross
        if: matrix.use-cross
        uses: taiki-e/install-action@cross
      
      - name: Build (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          if [[ "${{ matrix.use-cross }}" == "true" ]]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi
      
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/snapsafe.exe dist/
          else
            cp target/${{ matrix.target }}/release/snapsafe dist/
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapsafe-${{ matrix.target }}
          path: dist

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Display structure of downloaded files
        run: find artifacts -type f | sort
        
      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f -name "snapsafe*" -exec cp {} release-assets/ \;
          ls -la release-assets/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release-assets/*
          generate_release_notes: true
