name: Release

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        features: [--all-features]
        target: [""]
        include:
          - os: ubuntu-latest
            rust: stable
            features: ""
          - os: ubuntu-latest
            rust: beta
            features: --all-features
          - os: ubuntu-latest
            rust: stable
            features: --all-features
            target: --target armv5te-unknown-linux-gnueabi
            use-cross: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/snapsafe.exe dist/
          else
            cp target/${{ matrix.target }}/release/snapsafe dist/
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapsafe-${{ matrix.target }}
          path: dist/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/snapsafe-*/snapsafe*
          generate_release_notes: true